- hosts: pd
  tasks:
   - name: Add group "sysadmins" to remote server
     group:
       name: sysadmins
       gid: 2010
       state: present

   - name: Add user "lzwang" to remote server
     user:
       name: lzwang
       comment: "LZWANG"
       uid: 2001
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
       password: ''

   - name: give sudo access to "lzwang"
     blockinfile:
       path: /etc/sudoers
       insertafter: "root    ALL=(ALL)       ALL"
       block: |
         lzwang    ALL=(ALL)       ALL



