- hosts: pd
  vars:
    lzwang_passwd: "002208"
  tasks:
   - name: Add user "lzwang" to remote server
     user:
       name: lzwang
       comment: "LZWANG"
       uid: 2001
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
       update_password: always
       password: "{{ lzwang_passwd|password_hash('sha512') }}"

   - name: give sudo access to "lzwang"
     blockinfile:
       path: /etc/sudoers
       insertafter: "root    ALL=(ALL)       ALL"
       block: |
         lzwang    ALL=(ALL)       ALL



