- hosts: pd
  vars:
    - gogs_url: "https://github.com/gogs/gogs/releases/download/v0.12.3/gogs_0.12.3_linux_amd64.tar.gz"
    - mygit_passwd: "mygit@GOGS"
  tasks:
    - name: Add user "mygit" to remote server
      user:
        name: mygit
        comment: "Git service user"
        uid: 2002
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        update_password: always
        password: "{{ mygit_passwd|password_hash('sha512') }}"

    - name: Get binary gogs packages
      get_url:
        url: "{{ gogs_url }}"
        dest: "/home/mygit/"

    - name: Unachive Packages
      shell: "tar -zxvf /home/mygit/gogs*.tar.gz -C /home/mygit/ && \
              chown mygit:mygit /home/mygit -R "

    - name: Register gogs service by template
      copy:
        src: /Users/lzwang/MyAnsible/template/gogs/gogs.service
        dest: /etc/systemd/system/gogs.service

    - name: Enable && Start gogs service
      shell: "systemctl enable gogs.service && \
              systemctl start gogs.service"