- hosts: pd
  vars:
    config_local: /Users/lzwang/xfce_bak/2021-06-09
    config_remote: /home/lzwang/.config
    cfgs:
      - "xfce4"
      - "Thunar"
      - "Mousepad"
  tasks:
    - name: remove current settings
      shell: "rm -rf {{ config_remote }}/{{ item }} && \
              mkdir {{ config_remote }}/{{ item }}"
      loop:  "{{ cfgs }}"

    - name: Unarchive xfce4 config to remote
      unarchive: 
        src: "{{ config_local }}/{{ item }}.tar.gz"
        dest: "{{ config_remote }}/{{ item }}"
      loop:  "{{ cfgs }}"

    - name: grant permission
      shell: "chown lzwang: ~lzwang /home/lzwang/.config -R"

    - name: reboot and make settings works
      reboot:
        reboot_timeout: 300
        msg: "reboot {{ inventory_hostname }} success"
