- hosts: pd
  tasks:
    - name: install sublime (1/3 Install the GPG key)
      shell: "rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg"

    - name: install sublime (2/3 Select the channel to use)
      shell: "sudo dnf config-manager --add-repo \
              https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo"

    - name: install sublime (3/3 Update dnf and install Sublime Text)
      shell: "dnf install sublime-text -y"




