- hosts: pd
  gather_facts: False
  vars:
    - fedora_repo: /etc/yum.repos.d/fedora.repo
    - fedora_updates_repo: /etc/yum.repos.d/fedora-updates.repo
    - fedora_modular_repo: /etc/yum.repos.d/fedora-modular.repo
    - fedora_updates_modular_repo: /etc/yum.repos.d/fedora-updates-modular.repo

  tasks:
    - name: fedora.repo
      stat: 
        path: "{{ fedora_repo }}"
      register: fedora_repo_path
    - name: Check that if {{ fedora_repo }} exists
      debug:
        msg: "{{ fedora_repo }} exists."
      when: fedora_repo_path.stat.exists == True
    - name: backup {{ fedora_repo }}
      shell: mv "{{ fedora_repo }}" "{{ fedora_repo }}".bak
      when: fedora_repo_path.stat.exists == True

    - name: fedora-updates.repo
      stat: 
        path: "{{ fedora_updates_repo }}"
      register: fedora_updates_repo_path
    - name: Check that if {{ fedora_updates_repo }} exists
      debug:
        msg: "{{ fedora_updates_repo }} exists."
      when: fedora_updates_repo_path.stat.exists == True
    - name: backup {{ fedora_updates_repo }}
      shell: mv "{{ fedora_updates_repo }}" "{{ fedora_updates_repo }}".bak
      when: fedora_updates_repo_path.stat.exists == True

    - name: fedora-modular.repo
      stat: 
        path: "{{ fedora_modular_repo }}"
      register: fedora_modular_repo_path
    - name: Check that if {{ fedora_modular_repo }} exists
      debug:
        msg: "{{ fedora_modular_repo }} exists."
      when: fedora_modular_repo_path.stat.exists == True
    - name: backup {{ fedora_modular_repo }}
      shell: mv "{{ fedora_modular_repo }}" "{{ fedora_modular_repo }}".bak
      when: fedora_modular_repo_path.stat.exists == True

    - name: fedora-updates-modular.repo
      stat: 
        path: "{{ fedora_updates_modular_repo }}"
      register: fedora_updates_modular_repo_path
    - name: Check that if {{ fedora_updates_modular_repo }} exists
      debug:
        msg: "{{ fedora_updates_modular_repo }} exists."
      when: fedora_updates_modular_repo_path.stat.exists == True
    - name: backup {{ fedora_updates_modular_repo }}
      shell: mv "{{ fedora_updates_modular_repo }}" "{{ fedora_updates_modular_repo }}".bak
      when: fedora_updates_modular_repo_path.stat.exists == True

    - name: setup tsinghua Fedora source
      copy: src=/Users/lzwang/AnsibleTest/ansible/template/yum.repo.d/fedora33/ dest=/etc/yum.repos.d backup=yes

    - name: make tsinghua Fedora source
      shell: sudo dnf makecache
