- hosts: pd
  tasks:
    - name: setup tsinghua mirror
      shell: "sed -e 's|^mirrorlist=|#mirrorlist=|g' \
              -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g' \
              -i.bak \
              /etc/yum.repos.d/CentOS-*.repo"

    - name: yum clean all && yum makecache
      shell: "yum clean all && yum makecache"

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest